### ISSUE TITLE
composer.json file is useless

### ISSUE THREAD

**Issue by honzabrecka** [pwfisher/CommandLine.php#6]
composer.json file is useless until **you create** pwfisher/command-line-php package on packagist.org

Please, create it.

**Comment by andreyvital** [comment]
I agree.

@pwfisher can you?

**Comment by MaffooBristol** [comment]
Same here, was wondering why it wasn't working...

**Comment by pwfisher** [comment]
OK, done.

https://packagist.org/packages/pwfisher/command-line-php

**Comment by pwfisher** [comment]
And thanks for reporting this issue!

**Comment by andreyvital** [comment]
:+1: :beers:
@pwfisher.
