### ISSUE TITLE
travis-ci

### ISSUE THREAD

**Issue by honzabrecka** [pwfisher/CommandLine.php#7]
Now, when we have phpunit tests, we should use the travis-ci to automate the unit testing process.

I can prepare the .travis.yml file and help you with setup.

**Comment by pwfisher** [comment]
I'd be happy to accept a PR

**Comment by honzabrecka** [comment]
OK, here it is #8!

**Comment by SebSept** [comment]
:+1: 
@pwfisher , you now need to register on travis-ci, grab your token, configure your repo to add a service ...
